Allow secrets replacement in env.json (#189)

diff --git a/.github/workflows/instance.create.yml b/.github/workflows/instance.create.yml
--- a/.github/workflows/instance.create.yml
+++ b/.github/workflows/instance.create.yml
@@ -76,11 +76,38 @@ jobs:
         id: instance
         env:
           ENV_SOURCE_PATH: ./services/${{ github.event.inputs.service_id }}/env.json
+          SECRETS_CONTEXT: ${{ toJson(secrets) }}
         run: |
+          SERVICE_ID="${{ github.event.inputs.service_id }}"
+          ALLOWED_SECRET_KEY_PREFIX="${SERVICE_ID^^}_"
+
           ENV_VAR_OPTIONS=""
           if [ -f "$ENV_SOURCE_PATH" ]; then
             ENV_VAR_OPTIONS=$(./vendor/smartassert/bash-ga-ci-tools/src/output-json-scalar-object.sh "--env-var='{{ key }}={{ value }}' " < "$ENV_SOURCE_PATH")
           fi
+
+          SECRETS_PLACEHOLDERS=$(grep -Eo "\{\{ secrets\.[A-Za-z0-9_-]+ \}\}" <<< "$ENV_VAR_OPTIONS" | cat)
+
+          IFS=$'\n'
+          for item in $SECRETS_PLACEHOLDERS; do
+            SECRET_KEY_NAME="${item/"{{ secrets."/""}"
+            SECRET_KEY_NAME="${SECRET_KEY_NAME/" }}"/""}"
+
+            SECRET_EXISTS=$(jq "has(\"$SECRET_KEY_NAME\")" <<< "$SECRETS_CONTEXT")
+            if [ "false" = "$SECRET_EXISTS" ]; then
+              echo "Secret '$SECRET_KEY_NAME' has not been defined"
+              exit 1
+            fi
+
+            if [[ "$SECRET_KEY_NAME" != "$ALLOWED_SECRET_KEY_PREFIX"* ]]; then
+              echo "Secret '$SECRET_KEY_NAME' cannot be accessed by service '$SERVICE_ID'"
+              exit 2
+            fi
+
+            SECRET_VALUE=$(jq -r ".$SECRET_KEY_NAME" <<< "$SECRETS_CONTEXT")
+
+            ENV_VAR_OPTIONS="${ENV_VAR_OPTIONS//"{{ secrets.$SECRET_KEY_NAME }}"/"$SECRET_VALUE"}"
+          done
 
           COMMAND="php bin/console app:instance:create \
             $ENV_VAR_OPTIONS \
@@ -89,7 +116,7 @@ jobs:
             --image-id='${{ steps.image_id.outputs.image_id }}'"
 
           CREATE_OUTPUT=$(eval "$COMMAND")
-          echo "::set-output name=id::$(echo "$CREATE_OUTPUT" | jq ".id")"
+          echo "::set-output name=id::$(echo "$CREATE_OUTPUT" | jq -r ".id")"
 
       - name: Health check
         if: ${{ steps.build-config.outputs.health_check_url != '' }}
