Disallow access to secrets belonging to other services

diff --git a/.github/workflows/instance.create.yml b/.github/workflows/instance.create.yml
--- a/.github/workflows/instance.create.yml
+++ b/.github/workflows/instance.create.yml
@@ -78,6 +78,9 @@ jobs:
           ENV_SOURCE_PATH: ./services/${{ github.event.inputs.service_id }}/env.json
           SECRETS_CONTEXT: ${{ toJson(secrets) }}
         run: |
+          SERVICE_ID="${{ github.event.inputs.service_id }}"
+          ALLOWED_SECRET_KEY_PREFIX="$(echo ${SERVICE_ID^^})_"
+
           ENV_VAR_OPTIONS=""
           if [ -f "$ENV_SOURCE_PATH" ]; then
             ENV_VAR_OPTIONS=$(./vendor/smartassert/bash-ga-ci-tools/src/output-json-scalar-object.sh "--env-var='{{ key }}={{ value }}' " < "$ENV_SOURCE_PATH")
@@ -96,6 +99,11 @@ jobs:
               exit 1
             fi
 
+            if [[ $item != "$ALLOWED_SECRET_KEY_PREFIX"* ]]; then
+              echo "Secret '$SECRET_KEY_NAME' cannot be accessed by service '$SERVICE_ID'"
+              exit 2
+            fi
+
             SECRET_VALUE=$(jq -r ".$SECRET_KEY_NAME" <<< "$SECRETS_CONTEXT")
 
             ENV_VAR_OPTIONS="${ENV_VAR_OPTIONS//"{{ secrets.$SECRET_KEY_NAME }}"/"$SECRET_VALUE"}"
@@ -107,8 +115,10 @@ jobs:
             --collection-tag='${{ github.event.inputs.service_id }}' \
            --image-id='${{ steps.image_id.outputs.image_id }}'"
 
-          CREATE_OUTPUT=$(eval "$COMMAND")
-          echo "::set-output name=id::$(echo "$CREATE_OUTPUT" | jq ".id")"
+          echo "$COMMAND"
+
+          #CREATE_OUTPUT=$(eval "$COMMAND")
+          #echo "::set-output name=id::$(echo "$CREATE_OUTPUT" | jq ".id")"
 
 #      - name: Health check
 #        if: ${{ steps.build-config.outputs.health_check_url != '' }}
