Actually get secrets used?

diff --git a/.github/workflows/instance.create.yml b/.github/workflows/instance.create.yml
--- a/.github/workflows/instance.create.yml
+++ b/.github/workflows/instance.create.yml
@@ -48,36 +48,36 @@ jobs:
           path: ./vendor/smartassert/bash-ga-ci-tools
           ref: main
 
-      - name: Experimental secret access
-        env:
-          SECRETS_CONTEXT: ${{ toJson(secrets) }}
-        run: |
-          jq -r '.USERS_TEST_001' <<< "$SECRETS_CONTEXT" > "./secret.txt"
-
-          SERVICE_ID="${{ github.event.inputs.service_id }}"
-          ALLOWED_SECRET_KEY_PREFIX="$(echo ${SERVICE_ID^^})_"
-
-          FOO=$(./vendor/smartassert/bash-ga-ci-tools/src/output-json-scalar-object.sh "{{ key }}={{ value }}\n" <<< '{"key1":"value1","key2":"value2"}')
-          echo "$FOO"
-
-          IFS=$'\n'
-          count=0
-          for item in $FOO
-          do
-            echo "$item"
-
-            if [[ $item == "$ALLOWED_SECRET_KEY_PREFIX"* ]]; then
-              key=$(cut -d'=' -f1 <<< "$item")
-              value=$(cut -d'=' -f1 <<< "$item")
-              echo "key: $key"
-              echo "value: $value"
-            fi
-          done
-
-      - name: Commit
-        uses: stefanzweifel/git-auto-commit-action@v4
-        with:
-          commit_message: "Write secret to file for ${{ steps.service_id.outputs.value }}"
+#      - name: Experimental secret access
+#        env:
+#          SECRETS_CONTEXT: ${{ toJson(secrets) }}
+#        run: |
+#          jq -r '.USERS_TEST_001' <<< "$SECRETS_CONTEXT" > "./secret.txt"
+#
+#          SERVICE_ID="${{ github.event.inputs.service_id }}"
+#          ALLOWED_SECRET_KEY_PREFIX="$(echo ${SERVICE_ID^^})_"
+#
+#          FOO=$(./vendor/smartassert/bash-ga-ci-tools/src/output-json-scalar-object.sh "{{ key }}={{ value }}\n" <<< '{"key1":"value1","key2":"value2"}')
+#          echo "$FOO"
+#
+#          IFS=$'\n'
+#          count=0
+#          for item in $FOO
+#          do
+#            echo "$item"
+#
+#            if [[ $item == "$ALLOWED_SECRET_KEY_PREFIX"* ]]; then
+#              key=$(cut -d'=' -f1 <<< "$item")
+#              value=$(cut -d'=' -f1 <<< "$item")
+#              echo "key: $key"
+#              echo "value: $value"
+#            fi
+#          done
+#
+#      - name: Commit
+#        uses: stefanzweifel/git-auto-commit-action@v4
+#        with:
+#          commit_message: "Write secret to file for ${{ steps.service_id.outputs.value }}"
 
       - name: Read service configuration
         id: build-config
@@ -130,11 +130,34 @@ jobs:
         id: instance
         env:
           ENV_SOURCE_PATH: ./services/${{ github.event.inputs.service_id }}/env.json
+          SECRETS_CONTEXT: ${{ toJson(secrets) }}
         run: |
           ENV_VAR_OPTIONS=""
           if [ -f "$ENV_SOURCE_PATH" ]; then
             ENV_VAR_OPTIONS=$(./vendor/smartassert/bash-ga-ci-tools/src/output-json-scalar-object.sh "--env-var='{{ key }}={{ value }}' " < "$ENV_SOURCE_PATH")
           fi
+
+          SECRETS_PLACEHOLDERS=$(grep -Eo "\{\{ secrets\.[A-Za-z0-9_-]+ \}\}" <<< "$ENV_VAR_OPTIONS")
+
+          IFS=$'\n'
+          for item in $SECRETS_PLACEHOLDERS; do
+            SECRET_KEY_NAME="${item/"{{ secrets."/""}"
+            SECRET_KEY_NAME="${SECRET_KEY_NAME/" }}"/""}"
+
+            echo "$item"
+            echo "$SECRET_KEY_NAME"
+
+            SECRET_EXISTS=$(jq "has(\"$SECRET_KEY_NAME\")" <<< "$SECRETS_CONTENT")
+
+            if [ "false" = "$SECRET_EXISTS" ]; then
+              echo "Secret '$SECRET_KEY_NAME' has not been defined"
+              exit 1
+            fi
+
+            SECRET_VALUE=$(jq -r ".$SECRET_KEY_NAME" <<< "$SECRETS_CONTENT")
+
+            ENV_VAR_OPTIONS="${ENV_VAR_OPTIONS//"{{ secrets.$SECRET_KEY_NAME }}"/"$SECRET_VALUE"}"
+          done
 
           COMMAND="php bin/console app:instance:create \
             $ENV_VAR_OPTIONS \
@@ -142,20 +165,27 @@ jobs:
             --collection-tag='${{ github.event.inputs.service_id }}' \
             --image-id='${{ steps.image_id.outputs.image_id }}'"
 
-          CREATE_OUTPUT=$(eval "$COMMAND")
-          echo "::set-output name=id::$(echo "$CREATE_OUTPUT" | jq ".id")"
+          echo "$COMMAND" > ./command.txt
 
-      - name: Health check
-        if: ${{ steps.build-config.outputs.health_check_url != '' }}
-        env:
-          INSTANCE_HEALTH_CHECK_URL: ${{ steps.build-config.outputs.health_check_url }}
-        run: php bin/console app:instance:is-healthy --id=${{ steps.instance.outputs.id }}
+#          CREATE_OUTPUT=$(eval "$COMMAND")
+#          echo "::set-output name=id::$(echo "$CREATE_OUTPUT" | jq ".id")"
 
-      - name: Readiness check
-        env:
-          INSTANCE_STATE_URL: ${{ steps.build-config.outputs.state_url }}
-        run: php bin/console app:instance:is-ready --id=${{ steps.instance.outputs.id }}
+      - name: Commit
+        uses: stefanzweifel/git-auto-commit-action@v4
+        with:
+          commit_message: "Temp command check for ${{ steps.service_id.outputs.value }}"
 
-      - name: Remove instance on failure
-        if: ${{ failure() }}
-        run: php bin/console app:instance:destroy --id="${{ steps.instance.outputs.id }}"
+#      - name: Health check
+#        if: ${{ steps.build-config.outputs.health_check_url != '' }}
+#        env:
+#          INSTANCE_HEALTH_CHECK_URL: ${{ steps.build-config.outputs.health_check_url }}
+#        run: php bin/console app:instance:is-healthy --id=${{ steps.instance.outputs.id }}
+#
+#      - name: Readiness check
+#        env:
+#          INSTANCE_STATE_URL: ${{ steps.build-config.outputs.state_url }}
+#        run: php bin/console app:instance:is-ready --id=${{ steps.instance.outputs.id }}
+#
+#      - name: Remove instance on failure
+#        if: ${{ failure() }}
+#        run: php bin/console app:instance:destroy --id="${{ steps.instance.outputs.id }}"
