Store service configuration as json (#95)

diff --git a/.github/workflows/instance.create.yml b/.github/workflows/instance.create.yml
--- a/.github/workflows/instance.create.yml
+++ b/.github/workflows/instance.create.yml
@@ -18,21 +18,24 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v2
 
-      - name: Checkout bash-read-env-file
+      - name: Checkout bash-ga-ci-tools
         uses: actions/checkout@v2
         with:
-          repository: smartassert/bash-read-env-file
-          path: ./vendor/smartassert/bash-read-env-file
+          repository: smartassert/bash-ga-ci-tools
+          path: ./vendor/smartassert/bash-ga-ci-tools
           ref: main
 
       - name: Read service configuration
         id: build-config
         env:
-          ENV_FILE_PATH: ./services/${{ github.event.inputs.service_id }}/configuration.env
-          SERVICE_ID: ${{ github.event.inputs.service_id }}
+          CONFIGURATION_PATH: ./services/${{ github.event.inputs.service_id }}/configuration.json
         run: |
-          ./ci/scripts/check-service-configuration-exists.sh
-          ./vendor/smartassert/bash-read-env-file/src/read-env-file-ga.sh
+          if [ ! -f "$CONFIGURATION_PATH" ]; then
+            echo "Configuration for service ${{ github.event.inputs.service_id }} not found: $CONFIGURATION_PATH"
+            exit 1
+          fi
+
+          ./vendor/smartassert/bash-ga-ci-tools/src/create-ga-outputs-from-json-scalar-object.sh < "$CONFIGURATION_PATH"
 
       - name: Checkout bash-ga-deploy-tools
         uses: actions/checkout@v2
@@ -43,7 +46,7 @@ jobs:
 
       - name: Check snapshot exists
         env:
-          IMAGE_ID: ${{ steps.build-config.outputs.IMAGE_ID }}
+          IMAGE_ID: ${{ steps.build-config.outputs.image_id }}
           EXPECTED_EXISTS: "true"
         run: ./vendor/smartassert/bash-ga-deploy-tools/src/digitalocean-snapshot/verify-existence.sh
 
@@ -60,7 +63,7 @@ jobs:
       - name: Create
         id: instance
         env:
-          IMAGE_ID: ${{ steps.build-config.outputs.IMAGE_ID }}
+          IMAGE_ID: ${{ steps.build-config.outputs.image_id }}
           INSTANCE_COLLECTION_TAG: ${{ github.event.inputs.service_id }}
         run: |
           CREATE_OUTPUT=$(php bin/console app:instance:create)
@@ -69,7 +72,7 @@ jobs:
       - name: Health check
         env:
           INSTANCE_COLLECTION_TAG: ${{ github.event.inputs.service_id }}
-          INSTANCE_HEALTH_CHECK_URL: ${{ steps.build-config.outputs.HEALTH_CHECK_URL }}
+          INSTANCE_HEALTH_CHECK_URL: ${{ steps.build-config.outputs.health_check_url }}
         run: |
           HEALTH_CHECK_OUTPUT=$(php bin/console app:instance:is-healthy --id=${{ steps.instance.outputs.id }})
           HEALTH_CHECK_EXIT_CODE="$?"
diff --git a/.github/workflows/instances.destroy.yml b/.github/workflows/instances.destroy.yml
--- a/.github/workflows/instances.destroy.yml
+++ b/.github/workflows/instances.destroy.yml
@@ -18,21 +18,24 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v2
 
-      - name: Checkout bash-read-env-file
+      - name: Checkout bash-ga-ci-tools
         uses: actions/checkout@v2
         with:
-          repository: smartassert/bash-read-env-file
-          path: ./vendor/smartassert/bash-read-env-file
+          repository: smartassert/bash-ga-ci-tools
+          path: ./vendor/smartassert/bash-ga-ci-tools
           ref: main
 
       - name: Read service configuration
         id: build-config
         env:
-          ENV_FILE_PATH: ./services/${{ github.event.inputs.service_id }}/configuration.env
-          SERVICE_ID: ${{ github.event.inputs.service_id }}
+          CONFIGURATION_PATH: ./services/${{ github.event.inputs.service_id }}/configuration.json
         run: |
-          ./ci/scripts/check-service-configuration-exists.sh
-          ./vendor/smartassert/bash-read-env-file/src/read-env-file-ga.sh
+          if [ ! -f "$CONFIGURATION_PATH" ]; then
+            echo "Configuration for service ${{ github.event.inputs.service_id }} not found: $CONFIGURATION_PATH"
+            exit 1
+          fi
+
+          ./vendor/smartassert/bash-ga-ci-tools/src/create-ga-outputs-from-json-scalar-object.sh < "$CONFIGURATION_PATH"
 
       - name: Setup php
         uses: shivammathur/setup-php@v2
@@ -62,7 +65,7 @@ jobs:
         if: ${{ steps.ip.outputs.value != '' }}
         env:
           INSTANCE_COLLECTION_TAG: ${{ github.event.inputs.service_id }}
-          INSTANCE_STATE_URL: ${{ steps.build-config.outputs.STATE_URL }}
+          INSTANCE_STATE_URL: ${{ steps.build-config.outputs.state_url }}
           IP: ${{ steps.ip.outputs.value }}
         run: |
           INSTANCES=$(
