instance.create requires service_token_secret_name input

diff --git a/.github/workflows/instance.create.yml b/.github/workflows/instance.create.yml
--- a/.github/workflows/instance.create.yml
+++ b/.github/workflows/instance.create.yml
@@ -6,6 +6,9 @@ on:
       service_id:
         description: Service for which to create an instance
         required: true
+      service_token_secret_name:
+        description: Name of the repository secret to use as the service token
+        required: true
 
 jobs:
   create:
@@ -62,11 +65,6 @@ jobs:
           EXPECTED_EXISTS: "true"
         run: ./vendor/smartassert/bash-ga-deploy-tools/src/digitalocean-snapshot/verify-existence.sh
 
-      - name: Create service token
-        id: service_token
-        run: |
-          echo "::set-output name=value::$(openssl rand -hex 32)"
-
       - name: Setup php
         uses: shivammathur/setup-php@v2
         with:
@@ -77,12 +75,23 @@ jobs:
         with:
           args: --ignore-platform-reqs --quiet
 
+      - name: Verify service token secret exists and is of sufficient length
+        env:
+          SERVICE_TOKEN: ${{ secrets[github.event.inputs.service_token_secret_name] }}
+        run: |
+          TOKEN_LENGTH=$(($(wc -c <<< "$SERVICE_TOKEN")-1))
+
+          if [ "$TOKEN_LENGTH" -lt "32" ]; then
+            echo "Token secret not found or too short. Length: $TOKEN_LENGTH"
+            exit 1
+          fi
+
       - name: Create
         id: instance
         env:
           IMAGE_ID: ${{ steps.image_id.outputs.image_id }}
           INSTANCE_COLLECTION_TAG: ${{ github.event.inputs.service_id }}
-          SERVICE_TOKEN: ${{ steps.service_token.outputs.value }}
+          SERVICE_TOKEN: ${{ secrets[github.event.inputs.service_token_secret_name] }}
         run: |
           CREATE_OUTPUT=$(php bin/console app:instance:create)
           echo "::set-output name=id::$(echo "$CREATE_OUTPUT" | jq ".id")"
@@ -106,8 +115,15 @@ jobs:
           exit $HEALTH_CHECK_EXIT_CODE
 
       - name: Remove instance if health check failed
-        if:  ${{ failure() }}
+        if: ${{ failure() }}
         env:
           INSTANCE_ID: ${{ steps.instance.outputs.id }}
           INSTANCE_COLLECTION_TAG: ${{ github.event.inputs.service_id }}
         run: php bin/console app:instance:destroy --id="$INSTANCE_ID"
+
+      - name: Remove service token secret
+        if: ${{ always() }}
+        env:
+          GH_TOKEN: ${{ secrets.PAT_TOKEN_SELF }}
+        run: |
+          gh secret remove ${{ github.event.inputs.service_token_secret_name }}
