Verify service.configure resultant file contents (#497)

diff --git a/.github/workflows/test.service.configure.yml b/.github/workflows/test.service.configure.yml
--- a/.github/workflows/test.service.configure.yml
+++ b/.github/workflows/test.service.configure.yml
@@ -13,18 +13,24 @@ jobs:
       - name: Setup
         run: |
           SERVICE_ID=$(md5sum <<< "$RANDOM" | cut -d ' ' -f 1)
+          HEALTH_CHECK_URL=$(md5sum <<< "$RANDOM" | cut -d ' ' -f 1)
+          STATE_URL=$(md5sum <<< "$RANDOM" | cut -d ' ' -f 1)
           
           {
             echo "service_id=$SERVICE_ID"
             echo "branch_name=temp-$SERVICE_ID"
-            echo "service_directory=services/$SERVICE_ID"       
+            echo "service_directory=services/$SERVICE_ID"
+            echo "health_check_url=$HEALTH_CHECK_URL"
+            echo "state_url=$STATE_URL"
           } >> "$GITHUB_ENV"
 
       - name: Output setup
         run: |
           echo "service_id=${{ env.service_id }}"         
           echo "branch_name=${{ env.branch_name }}"
-          echo "service_directory=${{ env.service_directory }}"          
+          echo "service_directory=${{ env.service_directory }}"
+          echo "health_check_url=${{ env.health_check_url }}"
+          echo "state_url=${{ env.state_url }}"
 
       - name: Checkout
         uses: actions/checkout@v3
@@ -53,8 +59,8 @@ jobs:
           gh workflow run service.configure.yml \
           -r "${{ env.branch_name }}" \
           -f service_id="${{ env.service_id }}" \
-          -f state_url="/state" \
-          -f health_check_url="/health"
+          -f state_url="${{ env.state_url }}" \
+          -f health_check_url="${{ env.health_check_url }}"
 
       - name: Wait for service.configure to finish
         run: |
@@ -76,6 +82,25 @@ jobs:
           fi
           
           echo "$SERVICE_DIRECTORY exists."
+
+      - name: Verify generated file contents
+        run: |
+          CONFIGURATION_FILE_PATH="${{ env.service_directory }}/configuration.json"          
+          
+          HEALTH_CHECK_URL=$(jq -r '.health_check_url' < "$CONFIGURATION_FILE_PATH")
+          STATE_URL=$(jq -r '.state_url' < "$CONFIGURATION_FILE_PATH")
+          
+          if [ "$HEALTH_CHECK_URL" != "${{ env.health_check_url }}" ]; then
+            echo "health check url is invalid"
+            cat "$CONFIGURATION_FILE_PATH"
+            exit 1
+          fi
+          
+          if [ "$STATE_URL" != "${{ env.state_url }}" ]; then
+            echo "state url is invalid"
+            cat "$CONFIGURATION_FILE_PATH"
+            exit 1
+          fi
 
       - name: Delete temporary branch
         run: |
